### ISSUE TITLE
[Feature request] Support for scopedVars (repeating rows / panels)

### ISSUE THREAD

**Issue by brynjare** [OpenNMS/grafana-opennms-datasource#13]
The datasource currently doesn't support scopedVars, which is necessary to use repeating rows or panels with template variables.

Instead of having one graph per node, all repeating rows are duplicates containing a graph with the values from all selected nodes:

![opennms-scopedvars-request_4](https://cloud.githubusercontent.com/assets/1952603/23915805/6cd2603e-08ea-11e7-9364-99558fc6296f.gif)

By adding support for "options.scopedVars" in buildquery(), it should be possible to use [repeated rows](http://play.grafana.org/dashboard/db/repeated-rows) or [repeated panels](http://play.grafana.org/dashboard/db/templating-repeated-panels) with OpenNMS as the datasource.

**Comment by mmahacek** [comment]
I was about to submit this, but it you beat me to this.  Someone also submitted this to https://issues.opennms.org/browse/NMS-9217

**Comment by j-white** [comment]
Fixed in OpenNMS Helm 1.0.0.
