### ISSUE TITLE
Typo on the placeholder for the attribute.

### ISSUE THREAD

**Issue by agalue** [OpenNMS/grafana-opennms-datasource#3]
<img width="637" alt="typo" src="https://cloud.githubusercontent.com/assets/2521169/15509504/c8129936-21a1-11e6-9af5-9fca74af89e1.png">

As you can see on the attached screenshot, the placeholder says "Resource ID", it should be "Attribute Name" (or something similar).

**Comment by j-white** [comment]
Fixed in https://github.com/OpenNMS/grafana-opennms-datasource/commit/848270db7e444074ec6737cfb4356052b5413f71
