### ISSUE TITLE
Show node label when selecting variables in templates 

### ISSUE THREAD

**Issue by mhuot** [OpenNMS/grafana-opennms-datasource#4]
Currently the node id or foreign id show in the variable when selecting. This is not very useful for many users.

**Comment by deligatedgeek** [comment]
I think the OpenNMS Grafana integration is excellent, but it would be really great to see server name/node-label available in templates.  Our dashboard users would not be able to find the node if foreign id, etc.

Or if there was a way of forcing provisiond to use the servername as the foreign id, this would resolve some of this problem.

**Comment by j-white** [comment]
Fixed in https://github.com/OpenNMS/grafana-opennms-datasource/commit/c692eb80a862d77f6656c738f5f7d51658c7f9bd

**Comment by unicolet** [comment]
@j-white thanks for fixing this, however how does one use it? :blush: I can't seem to make it work on my installation (latest stable of everything) it always shows the foreign id:node id

**Comment by j-white** [comment]
@unicolet the node labels are only shown when using template variables.

This post explains how to use them: http://www.jessewhite.ca/opennms/grafana/2016/04/15/opennms-grafana-template-queries.html

**Comment by unicolet** [comment]
@j-white thanks again, I should have been more clear, my bad :-) I am able to get the node label in the template dropdown, but in the graph legend I only get 'foreignsource:foreignid', i.e.: 'servers:1648274'. Do I need to change the foreignid in the provisioning group?

**Comment by j-white** [comment]
Yeah, that's not currently possible. In this context only the "value" of the template variables can be show, and not their "label". Valid use case though, we could update the data-source to make this possible. See https://github.com/OpenNMS/grafana-opennms-datasource/issues/10.
