### ISSUE TITLE
Add support for Grafana 4

### ISSUE THREAD

**Issue by j-white** [OpenNMS/grafana-opennms-datasource#7]
When selecting metric attributes, the node dialog populates correctly but resources return empty.

**Comment by mattttt** [comment]
Hi @j-white, just wanted to let you know that we received a support inquiry today from a customer that upgraded to 4, but then had to downgrade and pin a 3.x version because of the DS.

thanks!

**Comment by j-white** [comment]
PR pending: https://github.com/grafana/grafana-plugin-repository/pull/82

**Comment by j-white** [comment]
PR was merged, 2.1.0 is now available.
